<%@ page language="java" contentType="text/html; charset=UTF-8"  
02.    pageEncoding="UTF-8"%> 03.
<%@ include file="/WEB-INF/page/common/tablib.jsp"%> 04.
<!doctype html> 05.
<html lang="zh">
	06.

	<head>
		07.
		<meta name='viewport' 08. content='width=device-width, initial-scale=1.0, maximum-scale=1.0' 09. charset="UTF-8" /> 10.
		<title></title>
		11.
		<script>
			12.
			var title = "选择";
			13. title += "城市";
			14. document.title = title;
			15.
			16.
		</script>
		17.
		<link rel="stylesheet" href="<%=basePath%>/css/base.css"> 18.
		<script src="<%=basePath%>/js/jquery-1.9.0.min.js"></script>
		19.
		<link rel="stylesheet" href="<%=basePath%>/partnercss/${style_path}.css"> 20.
		<style>
			21. 22. a:link,
			a:visited {
				23. text-decoration: none;
				/*超链接无下划线*/
				24. color: blue;
				25.
			}
			
			26. #float_zm {
				27. margin: 2% 2% 2% *;
				28. z-index: 90;
				29. width: 11%;
				30. height: 90%;
				31. right: 5px;
				32. position: fixed;
				33.
			}
			
			34. #city_div {
				35. padding: 0% 2% 2% 1%;
				36. width: 100%;
				37. float: left;
				38. margin-top: 2%;
				39.
			}
			
			40. #float_table {
				41. right: 5%;
				42. top: 9%;
				43. position: fixed;
				44. height: 90%;
				45. text-align: center;
				46. color: blue;
				47. width: 25%;
				48.
			}
			
			49. #float_table tr td {
				50. text-align: right;
				51.
			}
			
			52. #data {
				53. width: 100%;
				54.
			}
			
			55. #data tr td {
				56. border-bottom: 1px solid #e5e5e5;
				57. padding: 2% 1% 2% 1%;
				58.
			}
			
			59. #data tr td a {
				60. width: 100%;
				61.
			}
			
			62. .highlight {
				background: yellow;
				color: red;
			}
			
			63. 64. #showSelectZm {
				65. position: absolute;
				66. left: 45%;
				67. top: 40%;
				68. border: 3px solid #B2D0F7;
				69. padding: 10px;
				70. font: bold 14px verdana, tahoma, helvetica;
				71. color: #003366;
				72. width: 8%;
				73. text-align: center;
				74.
			}
			
			75. #seachInput {
				76. width: 78%;
				77.
			}
			
			78. #folat_top_div {
				79./*  
80.        //<!-比导航的字母高一点，不然点击点到字母上去了->  
81.        */
				82. z-index: 93;
				83. padding-top: 3%;
				84. position: fixed;
				85. padding-left: 5%;
				86. width: 95%;
				87. height: 9%;
				88. background-color: #efefef;
				89.
			}
			
			90. #body_div {
				91. float: left;
				92. width: 100%;
				93.
			}
			
			94. .zhanwei_div {
				95. height: 9%;
				96.
			}
			
			97. .fade {
				98. position: fixed;
				99. right: 0;
				100. bottom: 0;
				101. _position: absolute;
				102. _top: expression(documentElement.scrollTop+ documentElement.clientHeight-this.offsetHeight);
				103.
			}
			
			104. .formTips.fade {
				105. animation: 3s ease 0s normal both 1 running fade;
				106.
			}
			
			107. .fade {
				108. bottom: 0;
				109. position: fixed;
				110. right: 0;
				111.
			}
			
			112. .formTips {
				113. left: 0;
				114. position: absolute;
				115. text-align: center;
				116. width: 100%;
				117. z-index: 9999;
				118.
			}
			
			119. .formTips span {
				120. background: rgba(0, 0, 0, 0.6) none repeat scroll 0 0;
				121. border-radius: 5px;
				122. color: #fff;
				123. font-size: 14px;
				124. padding: 8px 10px;
				125.
			}
			
			126.
		</style>
		127.</head>
	128.

	<body class="wrapBg">
		129.
		<!-- 点击字母提示，暂未使用 -->
		130.
		<div id="showSelectZm" style="display: none;">
			131. <span id="showZmSpan"></span> 132.
		</div>
		133.
		<!-- 必须使用隐藏的，js中url参数会有问题(&) -->
		134.<input type="hidden" value="${last_url }" id="lastUrl"> 135. 136.
		<div id="folat_top_div">
			137. <input id="seachInput" name="seachInput" placeholder="输入城市中文名">
			<!-- 输入城市或城市首字母 -->
			138. <button id="seachButton">查找</button> 139. </div>
		140.
		<div id="body_div">
			141.
			<!-- 列表城市 -->
			142.
			<div id="city_div">
				143. 144.
				<table id="data">
					145. </table>
				146. </div>
			147. 148.
			<!-- 首字母索引层 -->
			149.
			<div id="float_zm" style="vertical-align: middle;">
				150.
				<table id="float_table">
					151. </table>
				152. </div>
			153. </div>
		154.</body>
	155.
	<script>
		156.
		var strChineseFirstPY = "YDYQSXMWZSSXJBYMGCCZQPSSQBYCDSCDQLDYLYBSSJGYZZJJFKCCLZDHWDWZJLJPFYYNWJJTMYHZWZHFLZPPQHGSCYYYNJQYXXGJHHSDSJNKKTMOMLCRXYPSNQSECCQZGGLLYJLMYZZSECYKYYHQWJSSGGYXYZYJWWKDJHYCHMYXJTLXJYQBYXZLDWRDJRWYSRLDZJPCBZJJBRCFTLECZSTZFXXZHTRQHYBDLYCZSSYMMRFMYQZPWWJJYFCRWFDFZQPYDDWYXKYJAWJFFXYPSFTZYHHYZYSWCJYXSCLCXXWZZXNBGNNXBXLZSZSBSGPYSYZDHMDZBQBZCWDZZYYTZHBTSYYBZGNTNXQYWQSKBPHHLXGYBFMJEBJHHGQTJCYSXSTKZHLYCKGLYSMZXYALMELDCCXGZYRJXSDLTYZCQKCNNJWHJTZZCQLJSTSTBNXBTYXCEQXGKWJYFLZQLYHYXSPSFXLMPBYSXXXYDJCZYLLLSJXFHJXPJBTFFYABYXBHZZBJYZLWLCZGGBTSSMDTJZXPTHYQTGLJSCQFZKJZJQNLZWLSLHDZBWJNCJZYZSQQYCQYRZCJJWYBRTWPYFTWEXCSKDZCTBZHYZZYYJXZCFFZZMJYXXSDZZOTTBZLQWFCKSZSXFYRLNYJMBDTHJXSQQCCSBXYYTSYFBXDZTGBCNSLCYZZPSAZYZZSCJCSHZQYDXLBPJLLMQXTYDZXSQJTZPXLCGLQTZWJBHCTSYJSFXYEJJTLBGXSXJMYJQQPFZASYJNTYDJXKJCDJSZCBARTDCLYJQMWNQNCLLLKBYBZZSYHQQLTWLCCXTXLLZNTYLNEWYZYXCZXXGRKRMTCNDNJTSYYSSDQDGHSDBJGHRWRQLYBGLXHLGTGXBQJDZPYJSJYJCTMRNYMGRZJCZGJMZMGXMPRYXKJNYMSGMZJYMKMFXMLDTGFBHCJHKYLPFMDXLQJJSMTQGZSJLQDLDGJYCALCMZCSDJLLNXDJFFFFJCZFMZFFPFKHKGDPSXKTACJDHHZDDCRRCFQYJKQCCWJDXHWJLYLLZGCFCQDSMLZPBJJPLSBCJGGDCKKDEZSQCCKJGCGKDJTJDLZYCXKLQSCGJCLTFPCQCZGWPJDQYZJJBYJHSJDZWGFSJGZKQCCZLLPSPKJGQJHZZLJPLGJGJJTHJJYJZCZMLZLYQBGJWMLJKXZDZNJQSYZMLJLLJKYWXMKJLHSKJGBMCLYYMKXJQLBMLLKMDXXKWYXYSLMLPSJQQJQXYXFJTJDXMXXLLCXQBSYJBGWYMBGGBCYXPJYGPEPFGDJGBHBNSQJYZJKJKHXQFGQZKFHYGKHDKLLSDJQXPQYKYBNQSXQNSZSWHBSXWHXWBZZXDMNSJBSBKBBZKLYLXGWXDRWYQZMYWSJQLCJXXJXKJEQXSCYETLZHLYYYSDZPAQYZCMTLSHTZCFYZYXYLJSDCJQAGYSLCQLYYYSHMRQQKLDXZSCSSSYDYCJYSFSJBFRSSZQSBXXPXJYSDRCKGJLGDKZJZBDKTCSYQPYHSTCLDJDHMXMCGXYZHJDDTMHLTXZXYLYMOHYJCLTYFBQQXPFBDFHHTKSQHZYYWCNXXCRWHOWGYJLEGWDQCWGFJYCSNTMYTOLBYGWQWESJPWNMLRYDZSZTXYQPZGCWXHNGPYXSHMYQJXZTDPPBFYHZHTJYFDZWKGKZBLDNTSXHQEEGZZYLZMMZYJZGXZXKHKSTXNXXWYLYAPSTHXDWHZYMPXAGKYDXBHNHXKDPJNMYHYLPMGOCSLNZHKXXLPZZLBMLSFBHHGYGYYGGBHSCYAQTYWLXTZQCEZYDQDQMMHTKLLSZHLSJZWFYHQSWSCWLQAZYNYTLSXTHAZNKZZSZZLAXXZWWCTGQQTDDYZTCCHYQZFLXPSLZYGPZSZNGLNDQTBDLXGTCTAJDKYWNSYZLJHHZZCWNYYZYWMHYCHHYXHJKZWSXHZYXLYSKQYSPSLYZWMYPPKBYGLKZHTYXAXQSYSHXASMCHKDSCRSWJPWXSGZJLWWSCHSJHSQNHCSEGNDAQTBAALZZMSSTDQJCJKTSCJAXPLGGXHHGXXZCXPDMMHLDGTYBYSJMXHMRCPXXJZCKZXSHMLQXXTTHXWZFKHCCZDYTCJYXQHLXDHYPJQXYLSYYDZOZJNYXQEZYSQYAYXWYPDGXDDXSPPYZNDLTWRHXYDXZZJHTCXMCZLHPYYYYMHZLLHNXMYLLLMDCPPXHMXDKYCYRDLTXJCHHZZXZLCCLYLNZSHZJZZLNNRLWHYQSNJHXYNTTTKYJPYCHHYEGKCTTWLGQRLGGTGTYGYHPYHYLQYQGCWYQKPYYYTTTTLHYHLLTYTTSPLKYZXGZWGPYDSSZZDQXSKCQNMJJZZBXYQMJRTFFBTKHZKBXLJJKDXJTLBWFZPPTKQTZTGPDGNTPJYFALQMKGXBDCLZFHZCLLLLADPMXDJHLCCLGYHDZFGYDDGCYYFGYDXKSSEBDHYKDKDKHNAXXYBPBYYHXZQGAFFQYJXDMLJCSQZLLPCHBSXGJYNDYBYQSPZWJLZKSDDTACTBXZDYZYPJZQSJNKKTKNJDJGYYPGTLFYQKASDNTCYHBLWDZHBBYDWJRYGKZYHEYYFJMSDTYFZJJHGCXPLXHLDWXXJKYTCYKSSSMTWCTTQZLPBSZDZWZXGZAGYKTYWXLHLSPBCLLOQMMZSSLCMBJCSZZKYDCZJGQQDSMCYTZQQLWZQZXSSFPTTFQMDDZDSHDTDWFHTDYZJYQJQKYPBDJYYXTLJHDRQXXXHAYDHRJLKLYTWHLLRLLRCXYLBWSRSZZSYMKZZHHKYHXKSMDSYDYCJPBZBSQLFCXXXNXKXWYWSDZYQOGGQMMYHCDZTTFJYYBGSTTTYBYKJDHKYXBELHTYPJQNFXFDYKZHQKZBYJTZBXHFDXKDASWTAWAJLDYJSFHBLDNNTNQJTJNCHXFJSRFWHZFMDRYJYJWZPDJKZYJYMPCYZNYNXFBYTFYFWYGDBNZZZDNYTXZEMMQBSQEHXFZMBMFLZZSRXYMJGSXWZJSPRYDJSJGXHJJGLJJYNZZJXHGXKYMLPYYYCXYTWQZSWHWLYRJLPXSLSXMFSWWKLCTNXNYNPSJSZHDZEPTXMYYWXYYSYWLXJQZQXZDCLEEELMCPJPCLWBXSQHFWWTFFJTNQJHJQDXHWLBYZNFJLALKYYJLDXHHYCSTYYWNRJYXYWTRMDRQHWQCMFJDYZMHMYYXJWMYZQZXTLMRSPWWCHAQBXYGZYPXYYRRCLMPYMGKSJSZYSRMYJSNXTPLNBAPPYPYLXYYZKYNLDZYJZCZNNLMZHHARQMPGWQTZMXXMLLHGDZXYHXKYXYCJMFFYYHJFSBSSQLXXNDYCANNMTCJCYPRRNYTYQNYYMBMSXNDLYLYSLJRLXYSXQMLLYZLZJJJKYZZCSFBZXXMSTBJGNXYZHLXNMCWSCYZYFZLXBRNNNYLBNRTGZQYSATSWRYHYJZMZDHZGZDWYBSSCSKXSYHYTXXGCQGXZZSHYXJSCRHMKKBXCZJYJYMKQHZJFNBHMQHYSNJNZYBKNQMCLGQHWLZNZSWXKHLJHYYBQLBFCDSXDLDSPFZPSKJYZWZXZDDXJSMMEGJSCSSMGCLXXKYYYLNYPWWWGYDKZJGGGZGGSYCKNJWNJPCXBJJTQTJWDSSPJXZXNZXUMELPXFSXTLLXCLJXJJLJZXCTPSWXLYDHLYQRWHSYCSQYYBYAYWJJJQFWQCQQCJQGXALDBZZYJGKGXPLTZYFXJLTPADKYQHPMATLCPDCKBMTXYBHKLENXDLEEGQDYMSAWHZMLJTWYGXLYQZLJEEYYBQQFFNLYXRDSCTGJGXYYNKLLYQKCCTLHJLQMKKZGCYYGLLLJDZGYDHZWXPYSJBZKDZGYZZHYWYFQYTYZSZYEZZLYMHJJHTSMQWYZLKYYWZCSRKQYTLTDXWCTYJKLWSQZWBDCQYNCJSRSZJLKCDCDTLZZZACQQZZDDXYPLXZBQJYLZLLLQDDZQJYJYJZYXNYYYNYJXKXDAZWYRDLJYYYRJLXLLDYXJCYWYWNQCCLDDNYYYNYCKCZHXXCCLGZQJGKWPPCQQJYSBZZXYJSQPXJPZBSBDSFNSFPZXHDWZTDWPPTFLZZBZDMYYPQJRSDZSQZSQXBDGCPZSWDWCSQZGMDHZXMWWFYBPDGPHTMJTHZSMMBGZMBZJCFZWFZBBZMQCFMBDMCJXLGPNJBBXGYHYYJGPTZGZMQBQTCGYXJXLWZKYDPDYMGCFTPFXYZTZXDZXTGKMTYBBCLBJASKYTSSQYYMSZXFJEWLXLLSZBQJJJAKLYLXLYCCTSXMCWFKKKBSXLLLLJYXTYLTJYYTDPJHNHNNKBYQNFQYYZBYYESSESSGDYHFHWTCJBSDZZTFDMXHCNJZYMQWSRYJDZJQPDQBBSTJGGFBKJBXTGQHNGWJXJGDLLTHZHHYYYYYYSXWTYYYCCBDBPYPZYCCZYJPZYWCBDLFWZCWJDXXHYHLHWZZXJTCZLCDPXUJCZZZLYXJJTXPHFXWPYWXZPTDZZBDZCYHJHMLXBQXSBYLRDTGJRRCTTTHYTCZWMXFYTWWZCWJWXJYWCSKYBZSCCTZQNHXNWXXKHKFHTSWOCCJYBCMPZZYKBNNZPBZHHZDLSYDDYTYFJPXYNGFXBYQXCBHXCPSXTYZDMKYSNXSXLHKMZXLYHDHKWHXXSSKQYHHCJYXGLHZXCSNHEKDTGZXQYPKDHEXTYKCNYMYYYPKQYYYKXZLTHJQTBYQHXBMYHSQCKWWYLLHCYYLNNEQXQWMCFBDCCMLJGGXDQKTLXKGNQCDGZJWYJJLYHHQTTTNWCHMXCXWHWSZJYDJCCDBQCDGDNYXZTHCQRXCBHZTQCBXWGQWYYBXHMBYMYQTYEXMQKYAQYRGYZSLFYKKQHYSSQYSHJGJCNXKZYCXSBXYXHYYLSTYCXQTHYSMGSCPMMGCCCCCMTZTASMGQZJHKLOSQYLSWTMXSYQKDZLJQQYPLSYCZTCQQPBBQJZCLPKHQZYYXXDTDDTSJCXFFLLCHQXMJLWCJCXTSPYCXNDTJSHJWXDQQJSKXYAMYLSJHMLALYKXCYYDMNMDQMXMCZNNCYBZKKYFLMCHCMLHXRCJJHSYLNMTJZGZGYWJXSRXCWJGJQHQZDQJDCJJZKJKGDZQGJJYJYLXZXXCDQHHHEYTMHLFSBDJSYYSHFYSTCZQLPBDRFRZTZYKYWHSZYQKWDQZRKMSYNBCRXQBJYFAZPZZEDZCJYWBCJWHYJBQSZYWRYSZPTDKZPFPBNZTKLQYHBBZPNPPTYZZYBQNYDCPJMMCYCQMCYFZZDCMNLFPBPLNGQJTBTTNJZPZBBZNJKLJQYLNBZQHKSJZNGGQSZZKYXSHPZSNBCGZKDDZQANZHJKDRTLZLSWJLJZLYWTJNDJZJHXYAYNCBGTZCSSQMNJPJYTYSWXZFKWJQTKHTZPLBHSNJZSYZBWZZZZLSYLSBJHDWWQPSLMMFBJDWAQYZTCJTBNNWZXQXCDSLQGDSDPDZHJTQQPSWLYYJZLGYXYZLCTCBJTKTYCZJTQKBSJLGMGZDMCSGPYNJZYQYYKNXRPWSZXMTNCSZZYXYBYHYZAXYWQCJTLLCKJJTJHGDXDXYQYZZBYWDLWQCGLZGJGQRQZCZSSBCRPCSKYDZNXJSQGXSSJMYDNSTZTPBDLTKZWXQWQTZEXNQCZGWEZKSSBYBRTSSSLCCGBPSZQSZLCCGLLLZXHZQTHCZMQGYZQZNMCOCSZJMMZSQPJYGQLJYJPPLDXRGZYXCCSXHSHGTZNLZWZKJCXTCFCJXLBMQBCZZWPQDNHXLJCTHYZLGYLNLSZZPCXDSCQQHJQKSXZPBAJYEMSMJTZDXLCJYRYYNWJBNGZZTMJXLTBSLYRZPYLSSCNXPHLLHYLLQQZQLXYMRSYCXZLMMCZLTZSDWTJJLLNZGGQXPFSKYGYGHBFZPDKMWGHCXMSGDXJMCJZDYCABXJDLNBCDQYGSKYDQTXDJJYXMSZQAZDZFSLQXYJSJZYLBTXXWXQQZBJZUFBBLYLWDSLJHXJYZJWTDJCZFQZQZZDZSXZZQLZCDZFJHYSPYMPQZMLPPLFFXJJNZZYLSJEYQZFPFZKSYWJJJHRDJZZXTXXGLGHYDXCSKYSWMMZCWYBAZBJKSHFHJCXMHFQHYXXYZFTSJYZFXYXPZLCHMZMBXHZZSXYFYMNCWDABAZLXKTCSHHXKXJJZJSTHYGXSXYYHHHJWXKZXSSBZZWHHHCWTZZZPJXSNXQQJGZYZYWLLCWXZFXXYXYHXMKYYSWSQMNLNAYCYSPMJKHWCQHYLAJJMZXHMMCNZHBHXCLXTJPLTXYJHDYYLTTXFSZHYXXSJBJYAYRSMXYPLCKDUYHLXRLNLLSTYZYYQYGYHHSCCSMZCTZQXKYQFPYYRPFFLKQUNTSZLLZMWWTCQQYZWTLLMLMPWMBZSSTZRBPDDTLQJJBXZCSRZQQYGWCSXFWZLXCCRSZDZMCYGGDZQSGTJSWLJMYMMZYHFBJDGYXCCPSHXNZCSBSJYJGJMPPWAFFYFNXHYZXZYLREMZGZCYZSSZDLLJCSQFNXZKPTXZGXJJGFMYYYSNBTYLBNLHPFZDCYFBMGQRRSSSZXYSGTZRNYDZZCDGPJAFJFZKNZBLCZSZPSGCYCJSZLMLRSZBZZLDLSLLYSXSQZQLYXZLSKKBRXBRBZCYCXZZZEEYFGKLZLYYHGZSGZLFJHGTGWKRAAJYZKZQTSSHJJXDCYZUYJLZYRZDQQHGJZXSSZBYKJPBFRTJXLLFQWJHYLQTYMBLPZDXTZYGBDHZZRBGXHWNJTJXLKSCFSMWLSDQYSJTXKZSCFWJLBXFTZLLJZLLQBLSQMQQCGCZFPBPHZCZJLPYYGGDTGWDCFCZQYYYQYSSCLXZSKLZZZGFFCQNWGLHQYZJJCZLQZZYJPJZZBPDCCMHJGXDQDGDLZQMFGPSYTSDYFWWDJZJYSXYYCZCYHZWPBYKXRYLYBHKJKSFXTZJMMCKHLLTNYYMSYXYZPYJQYCSYCWMTJJKQYRHLLQXPSGTLYYCLJSCPXJYZFNMLRGJJTYZBXYZMSJYJHHFZQMSYXRSZCWTLRTQZSSTKXGQKGSPTGCZNJSJCQCXHMXGGZTQYDJKZDLBZSXJLHYQGGGTHQSZPYHJHHGYYGKGGCWJZZYLCZLXQSFTGZSLLLMLJSKCTBLLZZSZMMNYTPZSXQHJCJYQXYZXZQZCPSHKZZYSXCDFGMWQRLLQXRFZTLYSTCTMJCXJJXHJNXTNRZTZFQYHQGLLGCXSZSJDJLJCYDSJTLNYXHSZXCGJZYQPYLFHDJSBPCCZHJJJQZJQDYBSSLLCMYTTMQTBHJQNNYGKYRQYQMZGCJKPDCGMYZHQLLSLLCLMHOLZGDYYFZSLJCQZLYLZQJESHNYLLJXGJXLYSYYYXNBZLJSSZCQQCJYLLZLTJYLLZLLBNYLGQCHXYYXOXCXQKYJXXXYKLXSXXYQXCYKQXQCSGYXXYQXYGYTQOHXHXPYXXXULCYEYCHZZCBWQBBWJQZSCSZSSLZYLKDESJZWMYMCYTSDSXXSCJPQQSQYLYYZYCMDJDZYWCBTJSYDJKCYDDJLBDJJSODZYSYXQQYXDHHGQQYQHDYXWGMMMAJDYBBBPPBCMUUPLJZSMTXERXJMHQNUTPJDCBSSMSSSTKJTSSMMTRCPLZSZMLQDSDMJMQPNQDXCFYNBFSDQXYXHYAYKQYDDLQYYYSSZBYDSLNTFQTZQPZMCHDHCZCWFDXTMYQSPHQYYXSRGJCWTJTZZQMGWJJTJHTQJBBHWZPXXHYQFXXQYWYYHYSCDYDHHQMNMTMWCPBSZPPZZGLMZFOLLCFWHMMSJZTTDHZZYFFYTZZGZYSKYJXQYJZQBHMBZZLYGHGFMSHPZFZSNCLPBQSNJXZSLXXFPMTYJYGBXLLDLXPZJYZJYHHZCYWHJYLSJEXFSZZYWXKZJLUYDTMLYMQJPWXYHXSKTQJEZRPXXZHHMHWQPWQLYJJQJJZSZCPHJLCHHNXJLQWZJHBMZYXBDHHYPZLHLHLGFWLCHYYTLHJXCJMSCPXSTKPNHQXSRTYXXTESYJCTLSSLSTDLLLWWYHDHRJZSFGXTSYCZYNYHTDHWJSLHTZDQDJZXXQHGYLTZPHCSQFCLNJTCLZPFSTPDYNYLGMJLLYCQHYSSHCHYLHQYQTMZYPBYWRFQYKQSYSLZDQJMPXYYSSRHZJNYWTQDFZBWWTWWRXCWHGYHXMKMYYYQMSMZHNGCEPMLQQMTCWCTMMPXJPJJHFXYYZSXZHTYBMSTSYJTTQQQYYLHYNPYQZLCYZHZWSMYLKFJXLWGXYPJYTYSYXYMZCKTTWLKSMZSYLMPWLZWXWQZSSAQSYXYRHSSNTSRAPXCPWCMGDXHXZDZYFJHGZTTSBJHGYZSZYSMYCLLLXBTYXHBBZJKSSDMALXHYCFYGMQYPJYCQXJLLLJGSLZGQLYCJCCZOTYXMTMTTLLWTGPXYMZMKLPSZZZXHKQYSXCTYJZYHXSHYXZKXLZWPSQPYHJWPJPWXQQYLXSDHMRSLZZYZWTTCYXYSZZSHBSCCSTPLWSSCJCHNLCGCHSSPHYLHFHHXJSXYLLNYLSZDHZXYLSXLWZYKCLDYAXZCMDDYSPJTQJZLNWQPSSSWCTSTSZLBLNXSMNYYMJQBQHRZWTYYDCHQLXKPZWBGQYBKFCMZWPZLLYYLSZYDWHXPSBCMLJBSCGBHXLQHYRLJXYSWXWXZSLDFHLSLYNJLZYFLYJYCDRJLFSYZFSLLCQYQFGJYHYXZLYLMSTDJCYHBZLLNWLXXYGYYHSMGDHXXHHLZZJZXCZZZCYQZFNGWPYLCPKPYYPMCLQKDGXZGGWQBDXZZKZFBXXLZXJTPJPTTBYTSZZDWSLCHZHSLTYXHQLHYXXXYYZYSWTXZKHLXZXZPYHGCHKCFSYHUTJRLXFJXPTZTWHPLYXFCRHXSHXKYXXYHZQDXQWULHYHMJTBFLKHTXCWHJFWJCFPQRYQXCYYYQYGRPYWSGSUNGWCHKZDXYFLXXHJJBYZWTSXXNCYJJYMSWZJQRMHXZWFQSYLZJZGBHYNSLBGTTCSYBYXXWXYHXYYXNSQYXMQYWRGYQLXBBZLJSYLPSYTJZYHYZAWLRORJMKSCZJXXXYXCHDYXRYXXJDTSQFXLYLTSFFYXLMTYJMJUYYYXLTZCSXQZQHZXLYYXZHDNBRXXXJCTYHLBRLMBRLLAXKYLLLJLYXXLYCRYLCJTGJCMTLZLLCYZZPZPCYAWHJJFYBDYYZSMPCKZDQYQPBPCJPDCYZMDPBCYYDYCNNPLMTMLRMFMMGWYZBSJGYGSMZQQQZTXMKQWGXLLPJGZBQCDJJJFPKJKCXBLJMSWMDTQJXLDLPPBXCWRCQFBFQJCZAHZGMYKPHYYHZYKNDKZMBPJYXPXYHLFPNYYGXJDBKXNXHJMZJXSTRSTLDXSKZYSYBZXJLXYSLBZYSLHXJPFXPQNBYLLJQKYGZMCYZZYMCCSLCLHZFWFWYXZMWSXTYNXJHPYYMCYSPMHYSMYDYSHQYZCHMJJMZCAAGCFJBBHPLYZYLXXSDJGXDHKXXTXXNBHRMLYJSLTXMRHNLXQJXYZLLYSWQGDLBJHDCGJYQYCMHWFMJYBMBYJYJWYMDPWHXQLDYGPDFXXBCGJSPCKRSSYZJMSLBZZJFLJJJLGXZGYXYXLSZQYXBEXYXHGCXBPLDYHWETTWWCJMBTXCHXYQXLLXFLYXLLJLSSFWDPZSMYJCLMWYTCZPCHQEKCQBWLCQYDPLQPPQZQFJQDJHYMMCXTXDRMJWRHXCJZYLQXDYYNHYYHRSLSRSYWWZJYMTLTLLGTQCJZYABTCKZCJYCCQLJZQXALMZYHYWLWDXZXQDLLQSHGPJFJLJHJABCQZDJGTKHSSTCYJLPSWZLXZXRWGLDLZRLZXTGSLLLLZLYXXWGDZYGBDPHZPBRLWSXQBPFDWOFMWHLYPCBJCCLDMBZPBZZLCYQXLDOMZBLZWPDWYYGDSTTHCSQSCCRSSSYSLFYBFNTYJSZDFNDPDHDZZMBBLSLCMYFFGTJJQWFTMTPJWFNLBZCMMJTGBDZLQLPYFHYYMJYLSDCHDZJWJCCTLJCLDTLJJCPDDSQDSSZYBNDBJLGGJZXSXNLYCYBJXQYCBYLZCFZPPGKCXZDZFZTJJFJSJXZBNZYJQTTYJYHTYCZHYMDJXTTMPXSPLZCDWSLSHXYPZGTFMLCJTYCBPMGDKWYCYZCDSZZYHFLYCTYGWHKJYYLSJCXGYWJCBLLCSNDDBTZBSCLYZCZZSSQDLLMQYYHFSLQLLXFTYHABXGWNYWYYPLLSDLDLLBJCYXJZMLHLJDXYYQYTDLLLBUGBFDFBBQJZZMDPJHGCLGMJJPGAEHHBWCQXAXHHHZCHXYPHJAXHLPHJPGPZJQCQZGJJZZUZDMQYYBZZPHYHYBWHAZYJHYKFGDPFQSDLZMLJXKXGALXZDAGLMDGXMWZQYXXDXXPFDMMSSYMPFMDMMKXKSYZYSHDZKXSYSMMZZZMSYDNZZCZXFPLSTMZDNMXCKJMZTYYMZMZZMSXHHDCZJEMXXKLJSTLWLSQLYJZLLZJSSDPPMHNLZJCZYHMXXHGZCJMDHXTKGRMXFWMCGMWKDTKSXQMMMFZZYDKMSCLCMPCGMHSPXQPZDSSLCXKYXTWLWJYAHZJGZQMCSNXYYMMPMLKJXMHLMLQMXCTKZMJQYSZJSYSZHSYJZJCDAJZYBSDQJZGWZQQXFKDMSDJLFWEHKZQKJPEYPZYSZCDWYJFFMZZYLTTDZZEFMZLBNPPLPLPEPSZALLTYLKCKQZKGENQLWAGYXYDPXLHSXQQWQCQXQCLHYXXMLYCCWLYMQYSKGCHLCJNSZKPYZKCQZQLJPDMDZHLASXLBYDWQLWDNBQCRYDDZTJYBKBWSZDXDTNPJDTCTQDFXQQMGNXECLTTBKPWSLCTYQLPWYZZKLPYGZCQQPLLKCCYLPQMZCZQCLJSLQZDJXLDDHPZQDLJJXZQDXYZQKZLJCYQDYJPPYPQYKJYRMPCBYMCXKLLZLLFQPYLLLMBSGLCYSSLRSYSQTMXYXZQZFDZUYSYZTFFMZZSMZQHZSSCCMLYXWTPZGXZJGZGSJSGKDDHTQGGZLLBJDZLCBCHYXYZHZFYWXYZYMSDBZZYJGTSMTFXQYXQSTDGSLNXDLRYZZLRYYLXQHTXSRTZNGZXBNQQZFMYKMZJBZYMKBPNLYZPBLMCNQYZZZSJZHJCTZKHYZZJRDYZHNPXGLFZTLKGJTCTSSYLLGZRZBBQZZKLPKLCZYSSUYXBJFPNJZZXCDWXZYJXZZDJJKGGRSRJKMSMZJLSJYWQSKYHQJSXPJZZZLSNSHRNYPZTWCHKLPSRZLZXYJQXQKYSJYCZTLQZYBBYBWZPQDWWYZCYTJCJXCKCWDKKZXSGKDZXWWYYJQYYTCYTDLLXWKCZKKLCCLZCQQDZLQLCSFQCHQHSFSMQZZLNBJJZBSJHTSZDYSJQJPDLZCDCWJKJZZLPYCGMZWDJJBSJQZSYZYHHXJPBJYDSSXDZNCGLQMBTSFSBPDZDLZNFGFJGFSMPXJQLMBLGQCYYXBQKDJJQYRFKZTJDHCZKLBSDZCFJTPLLJGXHYXZCSSZZXSTJYGKGCKGYOQXJPLZPBPGTGYJZGHZQZZLBJLSQFZGKQQJZGYCZBZQTLDXRJXBSXXPZXHYZYCLWDXJJHXMFDZPFZHQHQMQGKSLYHTYCGFRZGNQXCLPDLBZCSCZQLLJBLHBZCYPZZPPDYMZZSGYHCKCPZJGSLJLNSCDSLDLXBMSTLDDFJMKDJDHZLZXLSZQPQPGJLLYBDSZGQLBZLSLKYYHZTTNTJYQTZZPSZQZTLLJTYYLLQLLQYZQLBDZLSLYYZYMDFSZSNHLXZNCZQZPBWSKRFBSYZMTHBLGJPMCZZLSTLXSHTCSYZLZBLFEQHLXFLCJLYLJQCBZLZJHHSSTBRMHXZHJZCLXFNBGXGTQJCZTMSFZKJMSSNXLJKBHSJXNTNLZDNTLMSJXGZJYJCZXYJYJWRWWQNZTNFJSZPZSHZJFYRDJSFSZJZBJFZQZZHZLXFYSBZQLZSGYFTZDCSZXZJBQMSZKJRHYJZCKMJKHCHGTXKXQGLXPXFXTRTYLXJXHDTSJXHJZJXZWZLCQSBTXWXGXTXXHXFTSDKFJHZYJFJXRZSDLLLTQSQQZQWZXSYQTWGWBZCGZLLYZBCLMQQTZHZXZXLJFRMYZFLXYSQXXJKXRMQDZDMMYYBSQBHGZMWFWXGMXLZPYYTGZYCCDXYZXYWGSYJYZNBHPZJSQSYXSXRTFYZGRHZTXSZZTHCBFCLSYXZLZQMZLMPLMXZJXSFLBYZMYQHXJSXRXSQZZZSSLYFRCZJRCRXHHZXQYDYHXSJJHZCXZBTYNSYSXJBQLPXZQPYMLXZKYXLXCJLCYSXXZZLXDLLLJJYHZXGYJWKJRWYHCPSGNRZLFZWFZZNSXGXFLZSXZZZBFCSYJDBRJKRDHHGXJLJJTGXJXXSTJTJXLYXQFCSGSWMSBCTLQZZWLZZKXJMLTMJYHSDDBXGZHDLBMYJFRZFSGCLYJBPMLYSMSXLSZJQQHJZFXGFQFQBPXZGYYQXGZTCQWYLTLGWSGWHRLFSFGZJMGMGBGTJFSYZZGZYZAFLSSPMLPFLCWBJZCLJJMZLPJJLYMQDMYYYFBGYGYZMLYZDXQYXRQQQHSYYYQXYLJTYXFSFSLLGNQCYHYCWFHCCCFXPYLYPLLZYXXXXXKQHHXSHJZCFZSCZJXCPZWHHHHHAPYLQALPQAFYHXDYLUKMZQGGGDDESRNNZLTZGCHYPPYSQJJHCLLJTOLNJPZLJLHYMHEYDYDSQYCDDHGZUNDZCLZYZLLZNTNYZGSLHSLPJJBDGWXPCDUTJCKLKCLWKLLCASSTKZZDNQNTTLYYZSSYSSZZRYLJQKCQDHHCRXRZYDGRGCWCGZQFFFPPJFZYNAKRGYWYQPQXXFKJTSZZXSWZDDFBBXTBGTZKZNPZZPZXZPJSZBMQHKCYXYLDKLJNYPKYGHGDZJXXEAHPNZKZTZCMXCXMMJXNKSZQNMNLWBWWXJKYHCPSTMCSQTZJYXTPCTPDTNNPGLLLZSJLSPBLPLQHDTNJNLYYRSZFFJFQWDPHZDWMRZCCLODAXNSSNYZRESTYJWJYJDBCFXNMWTTBYLWSTSZGYBLJPXGLBOCLHPCBJLTMXZLJYLZXCLTPNCLCKXTPZJSWCYXSFYSZDKNTLBYJCYJLLSTGQCBXRYZXBXKLYLHZLQZLNZCXWJZLJZJNCJHXMNZZGJZZXTZJXYCYYCXXJYYXJJXSSSJSTSSTTPPGQTCSXWZDCSYFPTFBFHFBBLZJCLZZDBXGCXLQPXKFZFLSYLTUWBMQJHSZBMDDBCYSCCLDXYCDDQLYJJWMQLLCSGLJJSYFPYYCCYLTJANTJJPWYCMMGQYYSXDXQMZHSZXPFTWWZQSWQRFKJLZJQQYFBRXJHHFWJJZYQAZMYFRHCYYBYQWLPEXCCZSTYRLTTDMQLYKMBBGMYYJPRKZNPBSXYXBHYZDJDNGHPMFSGMWFZMFQMMBCMZZCJJLCNUXYQLMLRYGQZCYXZLWJGCJCGGMCJNFYZZJHYCPRRCMTZQZXHFQGTJXCCJEAQCRJYHPLQLSZDJRBCQHQDYRHYLYXJSYMHZYDWLDFRYHBPYDTSSCNWBXGLPZMLZZTQSSCPJMXXYCSJYTYCGHYCJWYRXXLFEMWJNMKLLSWTXHYYYNCMMCWJDQDJZGLLJWJRKHPZGGFLCCSCZMCBLTBHBQJXQDSPDJZZGKGLFQYWBZYZJLTSTDHQHCTCBCHFLQMPWDSHYYTQWCNZZJTLBYMBPDYYYXSQKXWYYFLXXNCWCXYPMAELYKKJMZZZBRXYYQJFLJPFHHHYTZZXSGQQMHSPGDZQWBWPJHZJDYSCQWZKTXXSQLZYYMYSDZGRXCKKUJLWPYSYSCSYZLRMLQSYLJXBCXTLWDQZPCYCYKPPPNSXFYZJJRCEMHSZMSXLXGLRWGCSTLRSXBZGBZGZTCPLUJLSLYLYMTXMTZPALZXPXJTJWTCYYZLBLXBZLQMYLXPGHDSLSSDMXMBDZZSXWHAMLCZCPJMCNHJYSNSYGCHSKQMZZQDLLKABLWJXSFMOCDXJRRLYQZKJMYBYQLYHETFJZFRFKSRYXFJTWDSXXSYSQJYSLYXWJHSNLXYYXHBHAWHHJZXWMYLJCSSLKYDZTXBZSYFDXGXZJKHSXXYBSSXDPYNZWRPTQZCZENYGCXQFJYKJBZMLJCMQQXUOXSLYXXLYLLJDZBTYMHPFSTTQQWLHOKYBLZZALZXQLHZWRRQHLSTMYPYXJJXMQSJFNBXYXYJXXYQYLTHYLQYFMLKLJTMLLHSZWKZHLJMLHLJKLJSTLQXYLMBHHLNLZXQJHXCFXXLHYHJJGBYZZKBXSCQDJQDSUJZYYHZHHMGSXCSYMXFEBCQWWRBPYYJQTYZCYQYQQZYHMWFFHGZFRJFCDPXNTQYZPDYKHJLFRZXPPXZDBBGZQSTLGDGYLCQMLCHHMFYWLZYXKJLYPQHSYWMQQGQZMLZJNSQXJQSYJYCBEHSXFSZPXZWFLLBCYYJDYTDTHWZSFJMQQYJLMQXXLLDTTKHHYBFPWTYYSQQWNQWLGWDEBZWCMYGCULKJXTMXMYJSXHYBRWFYMWFRXYQMXYSZTZZTFYKMLDHQDXWYYNLCRYJBLPSXCXYWLSPRRJWXHQYPHTYDNXHHMMYWYTZCSQMTSSCCDALWZTCPQPYJLLQZYJSWXMZZMMYLMXCLMXCZMXMZSQTZPPQQBLPGXQZHFLJJHYTJSRXWZXSCCDLXTYJDCQJXSLQYCLZXLZZXMXQRJMHRHZJBHMFLJLMLCLQNLDXZLLLPYPSYJYSXCQQDCMQJZZXHNPNXZMEKMXHYKYQLXSXTXJYYHWDCWDZHQYYBGYBCYSCFGPSJNZDYZZJZXRZRQJJYMCANYRJTLDPPYZBSTJKXXZYPFDWFGZZRPYMTNGXZQBYXNBUFNQKRJQZMJEGRZGYCLKXZDSKKNSXKCLJSPJYYZLQQJYBZSSQLLLKJXTBKTYLCCDDBLSPPFYLGYDTZJYQGGKQTTFZXBDKTYYHYBBFYTYYBCLPDYTGDHRYRNJSPTCSNYJQHKLLLZSLYDXXWBCJQSPXBPJZJCJDZFFXXBRMLAZHCSNDLBJDSZBLPRZTSWSBXBCLLXXLZDJZSJPYLYXXYFTFFFBHJJXGBYXJPMMMPSSJZJMTLYZJXSWXTYLEDQPJMYGQZJGDJLQJWJQLLSJGJGYGMSCLJJXDTYGJQJQJCJZCJGDZZSXQGSJGGCXHQXSNQLZZBXHSGZXCXYLJXYXYYDFQQJHJFXDHCTXJYRXYSQTJXYEFYYSSYYJXNCYZXFXMSYSZXYYSCHSHXZZZGZZZGFJDLTYLNPZGYJYZYYQZPBXQBDZTZCZYXXYHHSQXSHDHGQHJHGYWSZTMZMLHYXGEBTYLZKQWYTJZRCLEKYSTDBCYKQQSAYXCJXWWGSBHJYZYDHCSJKQCXSWXFLTYNYZPZCCZJQTZWJQDZZZQZLJJXLSBHPYXXPSXSHHEZTXFPTLQYZZXHYTXNCFZYYHXGNXMYWXTZSJPTHHGYMXMXQZXTSBCZYJYXXTYYZYPCQLMMSZMJZZLLZXGXZAAJZYXJMZXWDXZSXZDZXLEYJJZQBHZWZZZQTZPSXZTDSXJJJZNYAZPHXYYSRNQDTHZHYYKYJHDZXZLSWCLYBZYECWCYCRYLCXNHZYDZYDYJDFRJJHTRSQTXYXJRJHOJYNXELXSFSFJZGHPZSXZSZDZCQZBYYKLSGSJHCZSHDGQGXYZGXCHXZJWYQWGYHKSSEQZZNDZFKWYSSTCLZSTSYMCDHJXXYWEYXCZAYDMPXMDSXYBSQMJMZJMTZQLPJYQZCGQHXJHHLXXHLHDLDJQCLDWBSXFZZYYSCHTYTYYBHECXHYKGJPXHHYZJFXHWHBDZFYZBCAPNPGNYDMSXHMMMMAMYNBYJTMPXYYMCTHJBZYFCGTYHWPHFTWZZEZSBZEGPFMTSKFTYCMHFLLHGPZJXZJGZJYXZSBBQSCZZLZCCSTPGXMJSFTCCZJZDJXCYBZLFCJSYZFGSZLYBCWZZBYZDZYPSWYJZXZBDSYUXLZZBZFYGCZXBZHZFTPBGZGEJBSTGKDMFHYZZJHZLLZZGJQZLSFDJSSCBZGPDLFZFZSZYZYZSYGCXSNXXCHCZXTZZLJFZGQSQYXZJQDCCZTQCDXZJYQJQCHXZTDLGSCXZSYQJQTZWLQDQZTQCHQQJZYEZZZPBWKDJFCJPZTYPQYQTTYNLMBDKTJZPQZQZZFPZSBNJLGYJDXJDZZKZGQKXDLPZJTCJDQBXDJQJSTCKNXBXZMSLYJCQMTJQWWCJQNJNLLLHJCWQTBZQYDZCZPZZDZYDDCYZZZCCJTTJFZDPRRTZTJDCQTQZDTJNPLZBCLLCTZSXKJZQZPZLBZRBTJDCXFCZDBCCJJLTQQPLDCGZDBBZJCQDCJWYNLLZYZCCDWLLXWZLXRXNTQQCZXKQLSGDFQTDDGLRLAJJTKUYMKQLLTZYTDYYCZGJWYXDXFRSKSTQTENQMRKQZHHQKDLDAZFKYPBGGPZREBZZYKZZSPEGJXGYKQZZZSLYSYYYZWFQZYLZZLZHWCHKYPQGNPGBLPLRRJYXCCSYYHSFZFYBZYYTGZXYLXCZWXXZJZBLFFLGSKHYJZEYJHLPLLLLCZGXDRZELRHGKLZZYHZLYQSZZJZQLJZFLNBHGWLCZCFJYSPYXZLZLXGCCPZBLLCYBBBBUBBCBPCRNNZCZYRBFSRLDCGQYYQXYGMQZWTZYTYJXYFWTEHZZJYWLCCNTZYJJZDEDPZDZTSYQJHDYMBJNYJZLXTSSTPHNDJXXBYXQTZQDDTJTDYYTGWSCSZQFLSHLGLBCZPHDLYZJYCKWTYTYLBNYTSDSYCCTYSZYYEBHEXHQDTWNYGYCLXTSZYSTQMYGZAZCCSZZDSLZCLZRQXYYELJSBYMXSXZTEMBBLLYYLLYTDQYSHYMRQWKFKBFXNXSBYCHXBWJYHTQBPBSBWDZYLKGZSKYHXQZJXHXJXGNLJKZLYYCDXLFYFGHLJGJYBXQLYBXQPQGZTZPLNCYPXDJYQYDYMRBESJYYHKXXSTMXRCZZYWXYQYBMCLLYZHQYZWQXDBXBZWZMSLPDMYSKFMZKLZCYQYCZLQXFZZYDQZPZYGYJYZMZXDZFYFYTTQTZHGSPCZMLCCYTZXJCYTJMKSLPZHYSNZLLYTPZCTZZCKTXDHXXTQCYFKSMQCCYYAZHTJPCYLZLYJBJXTPNYLJYYNRXSYLMMNXJSMYBCSYSYLZYLXJJQYLDZLPQBFZZBLFNDXQKCZFYWHGQMRDSXYCYTXNQQJZYYPFZXDYZFPRXEJDGYQBXRCNFYYQPGHYJDYZXGRHTKYLNWDZNTSMPKLBTHBPYSZBZTJZSZZJTYYXZPHSSZZBZCZPTQFZMYFLYPYBBJQXZMXXDJMTSYSKKBJZXHJCKLPSMKYJZCXTMLJYXRZZQSLXXQPYZXMKYXXXJCLJPRMYYGADYSKQLSNDHYZKQXZYZTCGHZTLMLWZYBWSYCTBHJHJFCWZTXWYTKZLXQSHLYJZJXTMPLPYCGLTBZZTLZJCYJGDTCLKLPLLQPJMZPAPXYZLKKTKDZCZZBNZDYDYQZJYJGMCTXLTGXSZLMLHBGLKFWNWZHDXUHLFMKYSLGXDTWWFRJEJZTZHYDXYKSHWFZCQSHKTMQQHTZHYMJDJSKHXZJZBZZXYMPAGQMSTPXLSKLZYNWRTSQLSZBPSPSGZWYHTLKSSSWHZZLYYTNXJGMJSZSUFWNLSOZTXGXLSAMMLBWLDSZYLAKQCQCTMYCFJBSLXCLZZCLXXKSBZQCLHJPSQPLSXXCKSLNHPSFQQYTXYJZLQLDXZQJZDYYDJNZPTUZDSKJFSLJHYLZSQZLBTXYDGTQFDBYAZXDZHZJNHHQBYKNXJJQCZMLLJZKSPLDYCLBBLXKLELXJLBQYCXJXGCNLCQPLZLZYJTZLJGYZDZPLTQCSXFDMNYCXGBTJDCZNBGBQYQJWGKFHTNPYQZQGBKPBBYZMTJDYTBLSQMPSXTBNPDXKLEMYYCJYNZCTLDYKZZXDDXHQSHDGMZSJYCCTAYRZLPYLTLKXSLZCGGEXCLFXLKJRTLQJAQZNCMBYDKKCXGLCZJZXJHPTDJJMZQYKQSECQZDSHHADMLZFMMZBGNTJNNLGBYJBRBTMLBYJDZXLCJLPLDLPCQDHLXZLYCBLCXZZJADJLNZMMSSSMYBHBSQKBHRSXXJMXSDZNZPXLGBRHWGGFCXGMSKLLTSJYYCQLTSKYWYYHYWXBXQYWPYWYKQLSQPTNTKHQCWDQKTWPXXHCPTHTWUMSSYHBWCRWXHJMKMZNGWTMLKFGHKJYLSYYCXWHYECLQHKQHTTQKHFZLDXQWYZYYDESBPKYRZPJFYYZJCEQDZZDLATZBBFJLLCXDLMJSSXEGYGSJQXCWBXSSZPDYZCXDNYXPPZYDLYJCZPLTXLSXYZYRXCYYYDYLWWNZSAHJSYQYHGYWWAXTJZDAXYSRLTDPSSYYFNEJDXYZHLXLLLZQZSJNYQYQQXYJGHZGZCYJCHZLYCDSHWSHJZYJXCLLNXZJJYYXNFXMWFPYLCYLLABWDDHWDXJMCXZTZPMLQZHSFHZYNZTLLDYWLSLXHYMMYLMBWWKYXYADTXYLLDJPYBPWUXJMWMLLSAFDLLYFLBHHHBQQLTZJCQJLDJTFFKMMMBYTHYGDCQRDDWRQJXNBYSNWZDBYYTBJHPYBYTTJXAAHGQDQTMYSTQXKBTZPKJLZRBEQQSSMJJBDJOTGTBXPGBKTLHQXJJJCTHXQDWJLWRFWQGWSHCKRYSWGFTGYGBXSDWDWRFHWYTJJXXXJYZYSLPYYYPAYXHYDQKXSHXYXGSKQHYWFDDDPPLCJLQQEEWXKSYYKDYPLTJTHKJLTCYYHHJTTPLTZZCDLTHQKZXQYSTEEYWYYZYXXYYSTTJKLLPZMCYHQGXYHSRMBXPLLNQYDQHXSXXWGDQBSHYLLPJJJTHYJKYPPTHYYKTYEZYENMDSHLCRPQFDGFXZPSFTLJXXJBSWYYSKSFLXLPPLBBBLBSFXFYZBSJSSYLPBBFFFFSSCJDSTZSXZRYYSYFFSYZYZBJTBCTSBSDHRTJJBYTCXYJEYLXCBNEBJDSYXYKGSJZBXBYTFZWGENYHHTHZHHXFWGCSTBGXKLSXYWMTMBYXJSTZSCDYQRCYTWXZFHMYMCXLZNSDJTTTXRYCFYJSBSDYERXJLJXBBDEYNJGHXGCKGSCYMBLXJMSZNSKGXFBNBPTHFJAAFXYXFPXMYPQDTZCXZZPXRSYWZDLYBBKTYQPQJPZYPZJZNJPZJLZZFYSBTTSLMPTZRTDXQSJEHBZYLZDHLJSQMLHTXTJECXSLZZSPKTLZKQQYFSYGYWPCPQFHQHYTQXZKRSGTTSQCZLPTXCDYYZXSQZSLXLZMYCPCQBZYXHBSXLZDLTCDXTYLZJYYZPZYZLTXJSJXHLPMYTXCQRBLZSSFJZZTNJYTXMYJHLHPPLCYXQJQQKZZSCPZKSWALQSBLCCZJSXGWWWYGYKTJBBZTDKHXHKGTGPBKQYSLPXPJCKBMLLXDZSTBKLGGQKQLSBKKTFXRMDKBFTPZFRTBBRFERQGXYJPZSSTLBZTPSZQZSJDHLJQLZBPMSMMSXLQQNHKNBLRDDNXXDHDDJCYYGYLXGZLXSYGMQQGKHBPMXYXLYTQWLWGCPBMQXCYZYDRJBHTDJYHQSHTMJSBYPLWHLZFFNYPMHXXHPLTBQPFBJWQDBYGPNZTPFZJGSDDTQSHZEAWZZYLLTYYBWJKXXGHLFKXDJTMSZSQYNZGGSWQSPHTLSSKMCLZXYSZQZXNCJDQGZDLFNYKLJCJLLZLMZZNHYDSSHTHZZLZZBBHQZWWYCRZHLYQQJBEYFXXXWHSRXWQHWPSLMSSKZTTYGYQQWRSLALHMJTQJSMXQBJJZJXZYZKXBYQXBJXSHZTSFJLXMXZXFGHKZSZGGYLCLSARJYHSLLLMZXELGLXYDJYTLFBHBPNLYZFBBHPTGJKWETZHKJJXZXXGLLJLSTGSHJJYQLQZFKCGNNDJSSZFDBCTWWSEQFHQJBSAQTGYPQLBXBMMYWXGSLZHGLZGQYFLZBYFZJFRYSFMBYZHQGFWZSYFYJJPHZBYYZFFWODGRLMFTWLBZGYCQXCDJYGZYYYYTYTYDWEGAZYHXJLZYYHLRMGRXXZCLHNELJJTJTPWJYBJJBXJJTJTEEKHWSLJPLPSFYZPQQBDLQJJTYYQLYZKDKSQJYYQZLDQTGJQYZJSUCMRYQTHTEJMFCTYHYPKMHYZWJDQFHYYXWSHCTXRLJHQXHCCYYYJLTKTTYTMXGTCJTZAYYOCZLYLBSZYWJYTSJYHBYSHFJLYGJXXTMZYYLTXXYPZLXYJZYZYYPNHMYMDYYLBLHLSYYQQLLNJJYMSOYQBZGDLYXYLCQYXTSZEGXHZGLHWBLJHEYXTWQMAKBPQCGYSHHEGQCMWYYWLJYJHYYZLLJJYLHZYHMGSLJLJXCJJYCLYCJPCPZJZJMMYLCQLNQLJQJSXYJMLSZLJQLYCMMHCFMMFPQQMFYLQMCFFQMMMMHMZNFHHJGTTHHKHSLNCHHYQDXTMMQDCYZYXYQMYQYLTDCYYYZAZZCYMZYDLZFFFMMYCQZWZZMABTBYZTDMNZZGGDFTYPCGQYTTSSFFWFDTZQSSYSTWXJHXYTSXXYLBYQHWWKXHZXWZNNZZJZJJQJCCCHYYXBZXZCYZTLLCQXYNJYCYYCYNZZQYYYEWYCZDCJYCCHYJLBTZYYCQWMPWPYMLGKDLDLGKQQBGYCHJXY";
		157. //此处收录了375个多音字,数据来自于http://www.51window.net/page/pinyin    
		158.
		var oMultiDiff = {
			"19969": "DZ",
			"19975": "WM",
			"19988": "QJ",
			"20048": "YL",
			"20056": "SC",
			"20060": "NM",
			"20094": "QG",
			"20127": "QJ",
			"20167": "QC",
			"20193": "YG",
			"20250": "KH",
			"20256": "ZC",
			"20282": "SC",
			"20285": "QJG",
			"20291": "TD",
			"20314": "YD",
			"20340": "NE",
			"20375": "TD",
			"20389": "YJ",
			"20391": "CZ",
			"20415": "PB",
			"20446": "YS",
			"20447": "SQ",
			"20504": "TC",
			"20608": "KG",
			"20854": "QJ",
			"20857": "ZC",
			"20911": "PF",
			"20504": "TC",
			"20608": "KG",
			"20854": "QJ",
			"20857": "ZC",
			"20911": "PF",
			"20985": "AW",
			"21032": "PB",
			"21048": "XQ",
			"21049": "SC",
			"21089": "YS",
			"21119": "JC",
			"21242": "SB",
			"21273": "SC",
			"21305": "YP",
			"21306": "QO",
			"21330": "ZC",
			"21333": "SDC",
			"21345": "QK",
			"21378": "CA",
			"21397": "SC",
			"21414": "XS",
			"21442": "SC",
			"21477": "JG",
			"21480": "TD",
			"21484": "ZS",
			"21494": "YX",
			"21505": "YX",
			"21512": "HG",
			"21523": "XH",
			"21537": "PB",
			"21542": "PF",
			"21549": "KH",
			"21571": "E",
			"21574": "DA",
			"21588": "TD",
			"21589": "O",
			"21618": "ZC",
			"21621": "KHA",
			"21632": "ZJ",
			"21654": "KG",
			"21679": "LKG",
			"21683": "KH",
			"21710": "A",
			"21719": "YH",
			"21734": "WOE",
			"21769": "A",
			"21780": "WN",
			"21804": "XH",
			"21834": "A",
			"21899": "ZD",
			"21903": "RN",
			"21908": "WO",
			"21939": "ZC",
			"21956": "SA",
			"21964": "YA",
			"21970": "TD",
			"22003": "A",
			"22031": "JG",
			"22040": "XS",
			"22060": "ZC",
			"22066": "ZC",
			"22079": "MH",
			"22129": "XJ",
			"22179": "XA",
			"22237": "NJ",
			"22244": "TD",
			"22280": "JQ",
			"22300": "YH",
			"22313": "XW",
			"22331": "YQ",
			"22343": "YJ",
			"22351": "PH",
			"22395": "DC",
			"22412": "TD",
			"22484": "PB",
			"22500": "PB",
			"22534": "ZD",
			"22549": "DH",
			"22561": "PB",
			"22612": "TD",
			"22771": "KQ",
			"22831": "HB",
			"22841": "JG",
			"22855": "QJ",
			"22865": "XQ",
			"23013": "ML",
			"23081": "WM",
			"23487": "SX",
			"23558": "QJ",
			"23561": "YW",
			"23586": "YW",
			"23614": "YW",
			"23615": "SN",
			"23631": "PB",
			"23646": "ZS",
			"23663": "ZT",
			"23673": "YG",
			"23762": "TD",
			"23769": "ZS",
			"23780": "QJ",
			"23884": "QK",
			"24055": "XH",
			"24113": "DC",
			"24162": "ZC",
			"24191": "GA",
			"24273": "QJ",
			"24324": "NL",
			"24377": "TD",
			"24378": "QJ",
			"24439": "PF",
			"24554": "ZS",
			"24683": "TD",
			"24694": "WE",
			"24733": "LK",
			"24925": "TN",
			"25094": "ZG",
			"25100": "XQ",
			"25103": "XH",
			"25153": "PB",
			"25170": "PB",
			"25179": "KG",
			"25203": "PB",
			"25240": "ZS",
			"25282": "FB",
			"25303": "NA",
			"25324": "KG",
			"25341": "ZY",
			"25373": "WZ",
			"25375": "XJ",
			"25384": "A",
			"25457": "A",
			"25528": "SD",
			"25530": "SC",
			"25552": "TD",
			"25774": "ZC",
			"25874": "ZC",
			"26044": "YW",
			"26080": "WM",
			"26292": "PB",
			"26333": "PB",
			"26355": "ZY",
			"26366": "CZ",
			"26397": "ZC",
			"26399": "QJ",
			"26415": "ZS",
			"26451": "SB",
			"26526": "ZC",
			"26552": "JG",
			"26561": "TD",
			"26588": "JG",
			"26597": "CZ",
			"26629": "ZS",
			"26638": "YL",
			"26646": "XQ",
			"26653": "KG",
			"26657": "XJ",
			"26727": "HG",
			"26894": "ZC",
			"26937": "ZS",
			"26946": "ZC",
			"26999": "KJ",
			"27099": "KJ",
			"27449": "YQ",
			"27481": "XS",
			"27542": "ZS",
			"27663": "ZS",
			"27748": "TS",
			"27784": "SC",
			"27788": "ZD",
			"27795": "TD",
			"27812": "O",
			"27850": "PB",
			"27852": "MB",
			"27895": "SL",
			"27898": "PL",
			"27973": "QJ",
			"27981": "KH",
			"27986": "HX",
			"27994": "XJ",
			"28044": "YC",
			"28065": "WG",
			"28177": "SM",
			"28267": "QJ",
			"28291": "KH",
			"28337": "ZQ",
			"28463": "TL",
			"28548": "DC",
			"28601": "TD",
			"28689": "PB",
			"28805": "JG",
			"28820": "QG",
			"28846": "PB",
			"28952": "TD",
			"28975": "ZC",
			"29100": "A",
			"29325": "QJ",
			"29575": "SL",
			"29602": "FB",
			"30010": "TD",
			"30044": "CX",
			"30058": "PF",
			"30091": "YSP",
			"30111": "YN",
			"30229": "XJ",
			"30427": "SC",
			"30465": "SX",
			"30631": "YQ",
			"30655": "QJ",
			"30684": "QJG",
			"30707": "SD",
			"30729": "XH",
			"30796": "LG",
			"30917": "PB",
			"31074": "NM",
			"31085": "JZ",
			"31109": "SC",
			"31181": "ZC",
			"31192": "MLB",
			"31293": "JQ",
			"31400": "YX",
			"31584": "YJ",
			"31896": "ZN",
			"31909": "ZY",
			"31995": "XJ",
			"32321": "PF",
			"32327": "ZY",
			"32418": "HG",
			"32420": "XQ",
			"32421": "HG",
			"32438": "LG",
			"32473": "GJ",
			"32488": "TD",
			"32521": "QJ",
			"32527": "PB",
			"32562": "ZSQ",
			"32564": "JZ",
			"32735": "ZD",
			"32793": "PB",
			"33071": "PF",
			"33098": "XL",
			"33100": "YA",
			"33152": "PB",
			"33261": "CX",
			"33324": "BP",
			"33333": "TD",
			"33406": "YA",
			"33426": "WM",
			"33432": "PB",
			"33445": "JG",
			"33486": "ZN",
			"33493": "TS",
			"33507": "QJ",
			"33540": "QJ",
			"33544": "ZC",
			"33564": "XQ",
			"33617": "YT",
			"33632": "QJ",
			"33636": "XH",
			"33637": "YX",
			"33694": "WG",
			"33705": "PF",
			"33728": "YW",
			"33882": "SR",
			"34067": "WM",
			"34074": "YW",
			"34121": "QJ",
			"34255": "ZC",
			"34259": "XL",
			"34425": "JH",
			"34430": "XH",
			"34485": "KH",
			"34503": "YS",
			"34532": "HG",
			"34552": "XS",
			"34558": "YE",
			"34593": "ZL",
			"34660": "YQ",
			"34892": "XH",
			"34928": "SC",
			"34999": "QJ",
			"35048": "PB",
			"35059": "SC",
			"35098": "ZC",
			"35203": "TQ",
			"35265": "JX",
			"35299": "JX",
			"35782": "SZ",
			"35828": "YS",
			"35830": "E",
			"35843": "TD",
			"35895": "YG",
			"35977": "MH",
			"36158": "JG",
			"36228": "QJ",
			"36426": "XQ",
			"36466": "DC",
			"36710": "JC",
			"36711": "ZYG",
			"36767": "PB",
			"36866": "SK",
			"36951": "YW",
			"37034": "YX",
			"37063": "XH",
			"37218": "ZC",
			"37325": "ZC",
			"38063": "PB",
			"38079": "TD",
			"38085": "QY",
			"38107": "DC",
			"38116": "TD",
			"38123": "YD",
			"38224": "HG",
			"38241": "XTC",
			"38271": "ZC",
			"38415": "YE",
			"38426": "KH",
			"38461": "YD",
			"38463": "AE",
			"38466": "PB",
			"38477": "XJ",
			"38518": "YT",
			"38551": "WK",
			"38585": "ZC",
			"38704": "XS",
			"38739": "LJ",
			"38761": "GJ",
			"38808": "SQ",
			"39048": "JG",
			"39049": "XJ",
			"39052": "HG",
			"39076": "CZ",
			"39271": "XT",
			"39534": "TD",
			"39552": "TD",
			"39584": "PB",
			"39647": "SB",
			"39730": "LG",
			"39748": "TPB",
			"40109": "ZQ",
			"40479": "ND",
			"40516": "HG",
			"40536": "HG",
			"40583": "QJ",
			"40765": "YQ",
			"40784": "QJ",
			"40840": "YK",
			"40863": "QJG"
		};
		159. //参数,中文字符串    
		160. //返回值:拼音首字母串数组    
		161.
		function makePy(str) {
			162.
			if(typeof(str) != "string")
				163.
			throw new Error(-1, "函数makePy需要字符串类型参数!");
			164.
			var arrResult = new Array(); //保存中间结果的数组    
			165.
			for(var i = 0, len = str.length; i < len; i++) {
				166. //获得unicode码    
				167.
				var ch = str.charAt(i);
				168. //检查该unicode码是否在处理范围之内,在则返回该码对映汉字的拼音首字母,不在则调用其它函数处理    
				169. arrResult.push(checkCh(ch));
				170.
			}
			171. //处理arrResult,返回所有可能的拼音首字母串数组    
			172.
			return mkRslt(arrResult);
			173.
		}
		174.
		function checkCh(ch) {
			175.
			var uni = ch.charCodeAt(0);
			176. //如果不在汉字处理范围之内,返回原字符,也可以调用自己的处理函数    
			177.
			if(uni > 40869 || uni < 19968)
				178.
			return ch; //dealWithOthers(ch);    
			179. //检查是否是多音字,是按多音字处理,不是就直接在strChineseFirstPY字符串中找对应的首字母    
			180.
			return(oMultiDiff[uni] ? oMultiDiff[uni] : (strChineseFirstPY.charAt(uni - 19968)));
			181.
		}
		182.
		function mkRslt(arr) {
			183.
			var arrRslt = [""];
			184.
			for(var i = 0, len = arr.length; i < len; i++) {
				185.
				var str = arr[i];
				186.
				var strlen = str.length;
				187.
				if(strlen == 1) {
					188.
					for(var k = 0; k < arrRslt.length; k++) {
						189. arrRslt[k] += str;
						190.
					}
					191.
				} else {
					192.
					var tmpArr = arrRslt.slice(0);
					193. arrRslt = [];
					194.
					for(k = 0; k < strlen; k++) {
						195. //复制一个相同的arrRslt    
						196.
						var tmp = tmpArr.slice(0);
						197. //把当前字符str[k]添加到每个元素末尾    
						198.
						for(var j = 0; j < tmp.length; j++) {
							199. tmp[j] += str.charAt(k);
							200.
						}
						201. //把复制并修改后的数组连接到arrRslt上    
						202. arrRslt = arrRslt.concat(tmp);
						203.
					}
					204.
				}
				205.
			}
			206.
			return arrRslt;
			207.
		}
		208. //两端去空格函数    
		209. String.prototype.trim = function() {
			return this.replace(/(^\s*)|(\s*$)/g, "");
		};
		210. //  
		211.
		function getPosition(obj) {
			212.
			var top = 0;
			213.
			var left = 0;
			214.
			var width = obj.offsetWidth;
			215.
			var height = obj.offsetHeight;
			216.
			while(obj.offsetParent) {
				217. top += obj.offsetTop;
				218. left += obj.offsetLeft;
				219. obj = obj.offsetParent;
				220.
			}
			221.
			return {
				"top": top,
				"left": left,
				"width": width,
				"height": height
			};
			222.
		}
		223.
		224.
		function getCityFirst(city) {
			225.
			if(city == '')
				226.
			return '#';
			227.
			var str = city.substring(0, 1);
			228. //多音字处理  
			229.
			if(str == '长')
				230.
			return 'C';
			231.
			else if(str == '佛')
				232.
			return 'F';
			233.
			else if(str == '乐')
				234.
			return 'L';
			235.
			else if(str == '重')
				236.
			return 'C';
			237.
			var arrRslt = makePy(str);
			238.
			return arrRslt[0];
			239.
		}
		240.
	</script>
	241.
	<script>
		242.
		243. //$("#data").html('');  
		244.
		245. //有序无重复字母列表  
		246.
		var sort_first_zm = []; //（城市首字母变量）  
		247.
		var j = 0; //城市首字母变量索引  
		248.
		var seachIndex = 0; //用来存放搜索的索引，当前查找到第几个  
		249.
		250. //添加无重复首字母，用于字母索引，传入参数：城市名  
		251.
		function addFirstZM(city) {
			252.
			var ishave = false;
			253.
			var first = getCityFirst(city);
			254.
			for(var i = 0; i < sort_first_zm.length; i++) {
				255.
				if(sort_first_zm[i] == first) {
					256. ishave = true;
					257.
					break;
					258.
				}
				259.
			}
			260.
			if(!ishave) {
				261. sort_first_zm[j] = first;
				262. j++;
				263.
			}
			264.
		}
		265.
		266. //seachInput文本框值改变事件  
		267.
		var sCurText;
		268.
		var flag = 0;
		269.
		270. //查找指定文本  
		271.
		function findTextInBody() {
			272. //去除所有高亮显示的样式  
			273. $(".highlight").removeClass("highlight");
			274. $("[name=highlight]").attr("name", "");
			275.
			276. //查找匹配   
			277.
			var searchText = $('#seachInput').val(); //获取你输入的关键字；  
			278.
			if(searchText == '')
				279.
			return;
			280.
			281.
			var index = $.trim($('#seachInput').val().toString()); //去掉两头空格  
			282.
			283. //选择包含文本框值的所有加上focus类样式，并把它（们）移到ul的最前面  
			284.
			285. //console.log($("td:contains('" + index + "')"));  
			286.
			287.
			var regExp = new RegExp(searchText, 'g'); //创建正则表达式，g表示全局的，如果不用g， 则查找到第一个就不会继续向下查找了；   
			288.
			var content = $("#data").text();
			289.
			if(!regExp.test(content)) {
				290. createTips('没有该城市');
				291. //showTips("没有搜索到该城市",_searchTop,3,_searchLeft);   
				292.
				return;
				293.
			} else {
				294.
				if(sCurText != searchText) {
					295. i = 0;
					296. sCurText = searchText;
					297.
				}
				298.
			}
			299.
			300. //高亮显示   
			301. $('#data').find('td').each(function() {
				302.
				var html = $(this).html();
				303. //将找到的关键字替换，加上highlight属性；  
				304.
				if(html.indexOf(searchText) > -1) {
					305. $(this).find('span').addClass("highlight");
					306. $(this).find('span').attr("name", "highlight");
					307. flag = 1;
					308.
				}
				309.
				/**  
310.            var newHtml = html.replace(regExp, '<span class="highlight">'+searchText+'</span>');   
311.            $(this).html(newHtml);//更新；   
312.            */
				313.
			});
			314.
			315. seachIndex = 0;
			316. console.log('总共查找到: ' + $(".highlight").size());
			317.
		}
		318.
		319. //文本框值改变后重置掉搜索按钮,并进行一次搜索和定位  
		320. $("#seachInput").keyup(function() {
			321. $("#seachButton").text('查找');
			322. findTextInBody();
			323.
		});
		324.
		325. //搜索按钮被点击  
		326. //$('#seachInput').keyup(function(){  
		327. $("#seachButton").click(function() {
			328.
			if($(this).text() == '查找')
				329. findTextInBody();
			330. findNextString();
			331.
			332.
		});
		333.
		334.
		function findNextString() {
			335.
			if(seachIndex >= $(".highlight").size())
				336. seachIndex = 0;
			337.
			if($(".highlight").size() >= 1) {
				338. console.log('开始查找第  ' + seachIndex + "  个");
				339.
				340. $("#seachButton").text("下一个");
				341. console.log($(".highlight").eq(seachIndex));
				342. //js滚动到页面指定位置定位方法  
				343. //document.getElementsByName("highlight")[seachIndex].scrollIntoView();  
				344.
				345. //获取查找文本框按钮以及高度  
				346.
				var _top = $("#folat_top_div").height();
				347. //设置查找当前索引的符合文本的显示文职  
				348. //$(".highlight").eq(seachIndex).offset({ top: _top + 10});   
				349.
				350. //console.log($.scrollTo($(".highlight"),$(".highlight").eq(seachIndex).offset().top));  
				351.
				352. //jquery滚动到页面指定位置定位方法  
				353. $("html,body").animate({
					scrollTop: $(".highlight").eq(seachIndex).offset().top - ($(window).height() * 0.07 + 20)
				}, 1);
				354.
			} else {
				355. $("#seachButton").text("查找");
				356.
			}
			357. seachIndex++;
			358.
		}
		359.
		360. //搜索无结果提示  
		361.
		var tipsDiv = '<div class="tipsClass"></div>';
		362. $('body').append(tipsDiv);
		363.
		function showTips(tips, height, time, left) {
			364.
			var windowWidth = document.documentElement.clientWidth;
			365. $('.tipsClass').text(tips);
			366. $('div.tipsClass').css({
				367. 'top': height + 'px',
				368. 'left': left + 'px',
				369. 'position': 'absolute',
				370. 'padding': '8px 6px',
				371. 'background': '#000000',
				372. 'font-size': 14 + 'px',
				373. 'font-weight': 900,
				374. 'margin': '0 auto',
				375. 'text-align': 'center',
				376. 'width': 'auto',
				377. 'color': '#fff',
				378. 'border-radius': '2px',
				379. 'opacity': '0.8',
				380. 'box-shadow': '0px 0px 10px #000',
				381. '-moz-box-shadow': '0px 0px 10px #000',
				382. '-webkit-box-shadow': '0px 0px 10px #000'
				383.
			}).show();
			384. setTimeout(function() {
				$('div.tipsClass').fadeOut();
			}, (time * 1000));
			385.
		}
		386.
		387. //定位字母位置  
		388.
		function dingweiByZm(zm) {
			389.
			var _top = $("#folat_top_div").height();
			390. createTips(zm);
			391. $("html,body").animate({
				scrollTop: $("span[name='" + zm + "']").offset().top - ($(window).height() * 0.07 + 20)
			}, 1);
			392.
		}
		393.
		394. //城市和字母索引列表展示  
		395. //参数，循环添加数据方法  
		396.
		function showCityTable(method) {
			397. //开始进行有序显示  
			398.
			for(var zm in sort_first_zm) {
				399.
				400.
				var now_zm = sort_first_zm[zm];
				401.
				var show_zm = sort_first_zm[zm];
				402. //为字母列表赋值  
				403.
				/**  
404.            原始js定位  
405.            var float_text = "<span name='showZmSpan_C' style='width:25%;' onclick=\"document.getElementsByName(\'";  
406.            //var float_text = "<a href='#";  
407.            if(now_zm == '')  
408.                now_zm = "#";  
409.            float_text += now_zm + "\')[0].scrollIntoView()\">" + now_zm;  
410.            */
				411.
				var float_text = "<span name='showZmSpan_C' style='width:25%;' onclick=\"dingweiByZm(\'";
				412. //var float_text = "<a href='#";  
				413.
				if(now_zm == '')
					414. now_zm = "#";
				415. float_text += now_zm + "\')\">" + now_zm;
				416. float_text += "</span>";
				417.
				var insert_float = document.getElementById("float_table").insertRow(document.getElementById("float_table").rows.length);
				418.
				var colZM = insert_float.insertCell(0);
				419.
				420. float_text = now_zm;
				421. colZM.innerHTML = float_text;
				422. //漂浮字母导航td点击事件  
				423. colZM.onclick = function() {
					424.
					var cli = $(this).html().trim();
					425. dingweiByZm(cli);
					426. //document.getElementsByName(cli)[0].scrollIntoView();  
					427.
				};
				428. //insert_float.insertCell(0).innerHTML = float_text;  
				429.
				430. //为城市列表赋值  
				431.
				var text = "<span name='" + now_zm + "'>" + now_zm + "</span>";
				432.
				433.
				var insert = document.getElementById("data").insertRow(document.getElementById("data").rows.length);
				434. insert.insertCell(0).innerHTML = text;
				435.
				436. method(show_zm);
				437.
			}
			438.
		}
		439.
		440. //将城市添加到列表中，以及添加事件  
		441. //参数：城市value（值）,城市名,当前展示的字母  
		442.
		function addHtmlToTable(city_code, city_desc, show_zm) {
			443.
			if(show_zm == getCityFirst(city_desc)) {
				444.
				var insert = document.getElementById("data").insertRow(document.getElementById("data").rows.length);
				445.
				var coll = insert.insertCell(0);
				446. coll.innerHTML = '<span onclick="gotoLast(' + city_code + ',\'' + city_desc + '\');">' +
					447. city_desc + '</span>';
				448. coll.onclick = function() {
					gotoLast(city_code, city_desc);
				};
				449. //insert.insertCell(1).innerHTML = '字母   ${li.city_first_zm}';  
				450.
			}
			451.
		}
		452.
		453. //如果是社保和公积金  
		454.
		if('${type}' == 'social' || '${type}' == 'provident') {
			455. < c: forEach
			var = "t"
			items = "${belongList}" >
				456. addFirstZM('${t.city_desc}');
			457. < /c:forEach>  
			458. //排序赋值  
			459. sort_first_zm = sort_first_zm.sort();
			460. //fruits.sort();    
			461. //fruits.reverse();   
			462.
			463. //console.log(document.getElementById("data"));  
			464. showCityTable(function data(show_zm) {
				465. < c: forEach
				var = "li"
				items = "${belongList}" >
					466. //console.log('${li.city_desc}');  
				467. addHtmlToTable('${li.city_code}', '${li.city_desc}', show_zm);
				468. < /c:forEach>  
				469.
			});
			470.
		}
		471.
		472.
		/**  
473.    for(var i = 0; i < '${belongList.size()}';i++){  
474.        console.log(i);  
475.        var da = '${belongList.size()}';  
476.        sort_first_zm[i] =   
477.    }  
478.    $("#data");  
479.    */
		480. $("span[name='showZmSpan_C']").each(function() {
			481. $(this).click(function(t) {
				482. console.log($(this));
				483. //$("#showZmSpan").css("top","45%");  
				484. $("#showZmSpan").css("display", "");
				485.
			});
			486.
		});
		487.
		488.
		function gotoLast(code, city) {
			489.
			var lasturl = document.getElementById("lastUrl").value;
			490.
			if(lasturl == '')
				491. lasturl = document.location.href;
			492.
			while(lasturl.indexOf('&undefined&') > -1 || lasturl.indexOf(' ') > -1 493. || lasturl.indexOf('city_code') > -1 || lasturl.indexOf('city') > -1 494. || lasturl.indexOf(' ') > -1) {
				495.
				496.
				if(lasturl.indexOf('city_code') > -1) {
					497.
					var top = lasturl.split('city_code')[0];
					498.
					var next = lasturl.split('city_code')[1].split("&")[1];
					499. lasturl = top + next;
					500.
				}
				501.
				if(lasturl.indexOf('&undefined&') > -1) {
					502. lasturl = lasturl.replace("&undefined&", "");
					503.
				}
				504.
				/**  
505.        if(lasturl.indexOf('undefined') > -1){  
506.            lasturl = lasturl.replace("undefined","");  
507.        }  
508.        */
				509.
				if(lasturl.indexOf(' ') > -1) {
					510. lasturl = lasturl.replace(" ", "");
					511.
				}
				512.
				if(lasturl.indexOf('city') > -1) {
					513.
					var top = lasturl.split('city')[0];
					514.
					var next = lasturl.split('city')[1].split("&")[1];
					515. lasturl = top + next;
					516.
				}
				517.
			}
			518.
			519.
			while(lasturl.indexOf('undefined') > -1) {
				520. lasturl = lasturl.replace("undefined", "");
				521.
			}
			522.
			while(lasturl.indexOf('&&') > -1) {
				523. lasturl = lasturl.replace("&&", "&");
				524.
			}
			525. window.location.href = lasturl + "&city_code=" + code + "&city=" + city;
			526.
		}
		527.
		528. /*提示框*/
		529.
		function createTips(msg) {
			530.
			var $tips = $('#formTips'),
				531. top = $(window).height() / 2;
			532.
			533.
			534.
			if($tips.length == 0) {
				535. $tips = $('<div class="formTips" id="formTips"><span></span></div>');
				536. $('body').append($tips);
				537. $tips.find('span').html(msg);
				538. $tips.css('top', top)
				539..addClass('fade');
				540.
			} else {
				541. $tips.removeClass('fade')
				542..find('span')
				543..html(msg);
				544. $tips.css('top', top)
				545..show()
				546..addClass('fade');
				547.
			}
			548.
		}
		549.
	</script>
	550.

</html>